<?php
$CONFIG = array (
  'instanceid' => '0',
  'passwordsalt' => '123',
  'secret' => '123',
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/nc_data',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'nextcloud',
#  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'http://localhost/nextcloud/',
  'loglevel' => 1,
  'logtimezone' => 'Europe/Berlin',
  'logfile' => '/var/nc_data/nextcloud.log',
  'log_rotate_size' => 1048576,
  'installed' => true,
  'filesystem_check_changes' => 1,
  'quota_include_external_storage' => false,
  'knowledgebaseenabled' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
#  'filelocking.enabled' => 'true',
#  'memcache.locking' => '\\OC\\Memcache\\Redis',
#  'redis' =>
#   array (
#    'host' => '/var/run/redis/redis.sock',
#    'port' => 0,
#    'timeout' => 0.0,
#  ),
  'appstore.experimental.enabled' => false,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => '***',
  'mail_domain' => '***',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '***',
  'mail_smtpport' => '587',
  'mail_smtpname' => '***',
  'mail_smtppassword' => '***',
  'maintenance' => false,
  'theme' => '',
  'enabledPreviewProviders' =>
   array(
   'OC\Preview\PNG',
   'OC\Preview\JPEG',
   'OC\Preview\GIF',
   'OC\Preview\BMP',
   'OC\Preview\XBitmap',
   'OC\Preview\MarkDown',
   'OC\Preview\MP3',
   'OC\Preview\TXT',
   'OC\Preview\Movie',
   ),
);
